language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - pulseaudio
      - libpulse-mainloop-glib0
script:
  - dbus-launch pulseaudio --start
  - cargo build --verbose --all
  - cargo test --verbose --all
