language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pulseaudio libpulse-mainloop-glib0
script:
  - dbus-launch pulseaudio --start
  - cargo build --verbose --all
  - cargo test --verbose --all
