language: rust
rust:
  - 1.31.0 # Minimum supported version
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - pulseaudio
      - libpulse-mainloop-glib0
script:
  - dbus-launch pulseaudio --start
  - cargo check --verbose --all
  - cargo test --verbose --all
