[package]
name = "libpulse-simple-binding"
version = "2.7.0"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
readme = "README.md"
description = """
A Rust language binding for the PulseAudio libpulse-simple library.
"""
keywords = ["binding", "pulse", "pulseaudio", "pulse-simple", "audio"]
homepage = "https://github.com/jnqnfe/pulse-binding-rust"
repository = "https://github.com/jnqnfe/pulse-binding-rust"
exclude = ["README.md"]

[dependencies]
libpulse-binding = { path = "../pulse-binding", version = "2.7", default-features = false }
libpulse-sys = { path = "../pulse-sys", version = "1.6", default-features = false }
libpulse-simple-sys = { path = "../pulse-sys-simple", version = "1.6", default-features = false }

[features]
default = ["latest_pa_common_compatibility"]

# PA version compatibility selection
# See the overall project `COMPATIBILITY.md` file for explanation.
#
# Alias targetting latest compatibility, with the exception only of that for a very new release
latest_pa_common_compatibility = ["pa_v12_compatibility"]
# Alias simply targetting latest compatibility
latest_pa_compatibility = ["pa_v12_compatibility"]
# Enables PA version 12 support
pa_v12_compatibility = [
    "libpulse-binding/pa_v12_compatibility",
    "libpulse-sys/pa_v12_compatibility",
    "libpulse-simple-sys/pa_v12_compatibility"
]

# DEPRECATED, use `pa_v12_compatibility` instead
pa_encoding_from_string = ["pa_v12_compatibility"]

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
