[package]
name = "libpulse-simple-binding"
version = "2.4.0"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
readme = "README.md"
description = """
A Rust language binding for the PulseAudio libpulse-simple library.
"""
keywords = ["binding", "pulse", "pulseaudio", "pulse-simple", "audio"]
homepage = "https://github.com/jnqnfe/pulse-binding-rust"
repository = "https://github.com/jnqnfe/pulse-binding-rust"
exclude = ["README.md"]

[dependencies]
libpulse-binding = { path = "../pulse-binding", version = "2.4", default-features = false }
libpulse-sys = { path = "../pulse-sys", version = "1.4", default-features = false }
libpulse-simple-sys = { path = "../pulse-sys-simple", version = "1.4", default-features = false }

[features]
default = ["pa_encoding_from_string"]
#Disable this feature for backwards compatibility with PA < v12
pa_encoding_from_string = ["libpulse-binding/pa_encoding_from_string", "libpulse-sys/pa_encoding_from_string", "libpulse-simple-sys/pa_encoding_from_string"]

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
