[package]
name = "libpulse-simple-binding"
version = "1.2.0"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
readme = "README.md"
description = """
A Rust language binding for the PulseAudio libpulse-simple library.
"""
keywords = ["binding", "pulse", "pulseaudio", "pulse-simple", "audio"]

[dependencies]
libpulse-binding = { path = "../pulse-binding", version = "1.2" }
libpulse-sys = { path = "../pulse-sys", version = "1.1" }
libpulse-simple-sys = { path = "../pulse-sys-simple", version = "1.1" }

[features]

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
