[package]
name = "libpulse-sys"
version = "1.0.5"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
description = """
A Rust language linking library for the PulseAudio libpulse library.
"""
keywords = ["sys", "binding", "pulse", "pulseaudio", "audio"]
links = "pulse"
build = "build.rs"

[dependencies]
libc = "0.2"

[features]
default = []
#include pa_encoding_from_string function, symbol for which might be missing
pa_encoding_from_string = []

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
