[package]
name = "libpulse-glib-binding"
version = "2.2.4"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
readme = "README.md"
description = """
A Rust language binding for the PulseAudio libpulse-mainloop-glib library.
"""
keywords = ["binding", "pulse", "pulseaudio", "pulse-mainloop-glib", "audio"]
homepage = "https://github.com/jnqnfe/pulse-binding-rust"
repository = "https://github.com/jnqnfe/pulse-binding-rust"
include = ["src/**/*", "Cargo.toml", "CHANGELOG.md", "../LICENSE-LGPL"]

[dependencies]
libpulse-binding = { path = "../pulse-binding", version = "2.2", default-features = false }
libpulse-mainloop-glib-sys = { path = "../pulse-sys-mainloop-glib", version = "1.3", default-features = false }

[features]
default = ["pa_encoding_from_string"]
#include format::Encoding::from_string method, for which the underlying C API symbol was missing before PA v12
pa_encoding_from_string = ["libpulse-binding/pa_encoding_from_string", "libpulse-mainloop-glib-sys/pa_encoding_from_string"]

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
