[package]
name = "libpulse-binding"
version = "2.2.6"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
readme = "README.md"
description = """
A Rust language binding for the PulseAudio libpulse library.
"""
keywords = ["binding", "pulse", "pulseaudio", "audio"]
homepage = "https://github.com/jnqnfe/pulse-binding-rust"
repository = "https://github.com/jnqnfe/pulse-binding-rust"
exclude = ["README.md"]

[dependencies]
libc = "0.2"
libpulse-sys = { path = "../pulse-sys", version = "1.3", default-features = false }

[features]
default = ["pa_encoding_from_string"]
#Disable this feature for backwards compatibility with PA < v12
pa_encoding_from_string = ["libpulse-sys/pa_encoding_from_string"]

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
