[package]
name = "libpulse-binding"
version = "1.2.1"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
readme = "README.md"
description = """
A Rust language binding for the PulseAudio libpulse library.
"""
keywords = ["binding", "pulse", "pulseaudio", "audio"]

[dependencies]
libc = "0.2"
libpulse-sys = { path = "../pulse-sys", version = "1.1" }

[features]
default = []
#include pa_encoding_from_string function, symbol for which might be missing
pa_encoding_from_string = ["libpulse-sys/pa_encoding_from_string"]

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
