[package]
name = "libpulse-binding"
version = "2.10.1"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
readme = "README.md"
description = """
A Rust language binding for the PulseAudio libpulse library.
"""
keywords = ["binding", "pulse", "pulseaudio", "audio"]
homepage = "https://github.com/jnqnfe/pulse-binding-rust"
repository = "https://github.com/jnqnfe/pulse-binding-rust"
exclude = ["README.md"]
edition = "2018"

[dependencies]
libc = "0.2"
libpulse-sys = { path = "../pulse-sys", version = "1.8", default-features = false }

[features]
default = ["pa_latest_common"]

# PA version compatibility selection
# See the overall project `COMPATIBILITY.md` file for explanation.
#
# Alias targetting latest compatibility, with the exception only of that for a very new release
pa_latest_common = ["pa_v12"]
# Alias simply targetting latest compatibility
pa_latest = ["pa_v12"]
# Enables PA version 12 support
pa_v12 = ["pa_v8", "libpulse-sys/pa_v12"]
# Enables PA version 8 support
pa_v8 = ["pa_v6", "libpulse-sys/pa_v8"]
# Enables PA version 6 support
pa_v6 = ["pa_v5", "libpulse-sys/pa_v6"]
# Enables PA version 5 support
pa_v5 = ["libpulse-sys/pa_v5"]

# Documentation generation
# This is intended for use with generation of documentation only. It enables inclusion of the latest
# supported PA version features, but without triggering the build scripts pkg-config check.
dox = ["libpulse-sys/dox"]

# All deprecated:
latest_pa_common_compatibility = ["pa_latest_common"]
latest_pa_compatibility = ["pa_latest"]
pa_v12_compatibility = ["pa_v12"]

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
