[package]
name = "libpulse-simple-sys"
version = "1.3.0"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
description = """
A Rust language linking library for the PulseAudio libpulse-simple library.
"""
keywords = ["sys", "pulse", "pulseaudio", "pulse-simple", "audio"]
links = "pulse-simple"
build = "build.rs"
homepage = "https://github.com/jnqnfe/pulse-binding-rust"
repository = "https://github.com/jnqnfe/pulse-binding-rust"

[dependencies]
libpulse-sys = { path = "../pulse-sys", version = "1.3" }

[features]

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
